title: Aimee Johnson
#email: chrishasz@gmail.com
#description: >-
#  I build people-first software teams and also open source software.
baseurl: ""
url: "aejohnson1.github.io"
favicon: /images/favicon.jpg
logo: /images/favicon.jpg

#Social [jekyll-seo-tag]
social:
  name: aejohnson1
  links:
    - https://www.linkedin.com/in/aimee-johnson-a3ba02249/
    - https://github.com/aejohnson1
#twitter:
#  username: chrishasz
#  card: summary

# Custom Navigation Links
header_pages:
  - name : blog
    title : Blog
    url : /blog
  #- name : spgo.md
  #  title : SPGo
  #  url : /spgo
  #- name : glob2caml.md
  #  title : Glob2Caml
  #  url : /glob2caml
  #- name : yaght.md
  #  title : yaght
  #  url : /yaght

# Blog Config
show_excerpts: true
permalink: "/blog/:year/:month/:day/:title/"
paginate: 5
paginate_path: "/blog/page:num/"

#Google Analytics
#google_analytics: UA-138720538-1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  aejohnson1
    linkedin: aimee-johnson-a3ba02249
    #twitter: chrishasz
    #rss: rss

# Build settings
markdown: kramdown
remote_theme: chrishasz/yaght
